# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e959c72d0789a8193f185232bd9fc00fc19a7a9f1274d755d2c2684fbd7823791db6a2eed5be456a0af394da65ece223bfabf0f201b2b39a66c45a730e5e6468
  http_basic_username: user
  http_basic_password: password

test:
  secret_key_base: 96c6eada34b85b07e313ea15e3b0e74c87ef28b957eaa8e0fb0b3e15d952ebd8fd58860843196c19451b2901ae557cbfcb93ca01f6ee6ef2a980cc5e33dfe4db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_basic_username: <%= ENV["HTTP_BASIC_USERNAME"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"]
